import "./globals.css";


import Header from "./ui/components/Header";
import { geistMono, geistSans, questrial } from "./fonts";

export const metadata = {
  title: "Centro Social Maximiliano Kolbe",
  description: "Generated by create next app",
  icons: "/favicon.png"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${questrial.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-[url(/bg-desk.png)]`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
